name: Volatility Squeeze Breakout (M15, */5)

on:
  schedule:
    - cron: "*/5 * * * *"  # reālais skrējiens ik 5 min (UTC)
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (test = sūta testa ziņu Telegram)"
        required: true
        default: "run"
        type: choice
        options:
          - run
          - test

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python version
        run: |
          which python
          python --version

      - name: Run TEST (Telegram smoke)
        if: ${{ inputs.mode == 'test' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -m src.selftest

      - name: Run bot (production)
        if: ${{ inputs.mode == 'run' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: |
          python main.py
